### ISSUE TITLE
New user make Branch user

### ISSUE THREAD

**Issue by dpdavids** [ytgov/jv#126]
Once an agent adds a request make the requestor an "Active" system user and a "Branch User".  
Create a filter or grid for active/inactive and branch users.  So user administration is easier.

**Comment by dpdavids** [comment]
The only way I could get the approver to see the request was making them an Active, Branch user.  Ideally these would be set and created on the fly as soon as I add them to the request.

**Comment by datajohnson** [comment]
Please test

**Comment by dpdavids** [comment]
Complete
